<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="Hardware" Id="{7c48af90-6723-4880-a33e-8559ccab70bd}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Hardware
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Hardware">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>